version: '3'

dotenv: ['.env']

vars:
  MIGRATIONS_PATH: ./db/migrations
  ENV_FILE: .env

tasks:
  test:
    cmds:
      - godotenv -f {{.ENV_FILE}} go test -v ./...

  lint:
    cmds:
      - golangci-lint run ./...

  run:
    cmds:
      - task: lint
      - godotenv -f {{.ENV_FILE}} go run ./cmd/app/app.go

  "migrate:create":
    cmds:
      - migrate create -ext sql -dir {{.MIGRATIONS_PATH}} -seq $NAME

  "migrate:up":
    cmds:
      - migrate -path '{{.MIGRATIONS_PATH}}' -database $DB_CONNECTION -verbose up

  "migrate:drop":
    cmds:
      - migrate -path {{.MIGRATIONS_PATH}} -database $DB_CONNECTION drop

  "gen:models":
    cmds:
      - sqlc generate