// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: post_queries.sql

package models

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const postById = `-- name: PostById :one
select 
	p.id,
  p.title,
  p.content,
  p.created_by_id,
  u.name as created_by_name,
  p.comments_count,
  p.created_at,
  p.updated_at
from posts p
join users u on u.id = p.created_by_id
where p.id = $1 and p.deleted_at is null
limit 1
`

type PostByIdRow struct {
	ID            uuid.UUID
	Title         string
	Content       string
	CreatedByID   uuid.UUID
	CreatedByName string
	CommentsCount int32
	CreatedAt     pgtype.Timestamp
	UpdatedAt     pgtype.Timestamp
}

func (q *Queries) PostById(ctx context.Context, id uuid.UUID) (PostByIdRow, error) {
	row := q.db.QueryRow(ctx, postById, id)
	var i PostByIdRow
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Content,
		&i.CreatedByID,
		&i.CreatedByName,
		&i.CommentsCount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const postCreate = `-- name: PostCreate :one
insert into posts (id, title, content, created_by_id)
values ($1, $2, $3, $4)
returning id, title, content, created_by_id, comments_count, created_at, updated_at, deleted_at
`

type PostCreateParams struct {
	ID          uuid.UUID
	Title       string
	Content     string
	CreatedByID uuid.UUID
}

func (q *Queries) PostCreate(ctx context.Context, arg PostCreateParams) (Post, error) {
	row := q.db.QueryRow(ctx, postCreate,
		arg.ID,
		arg.Title,
		arg.Content,
		arg.CreatedByID,
	)
	var i Post
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Content,
		&i.CreatedByID,
		&i.CommentsCount,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const postDelete = `-- name: PostDelete :exec
update posts
set deleted_at = now()
where id = $1
`

func (q *Queries) PostDelete(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, postDelete, id)
	return err
}

const postUpdate = `-- name: PostUpdate :one
update posts
set title = $2, content = $3, updated_at = now()
where id = $1
returning id, title, content, created_by_id, comments_count, created_at, updated_at, deleted_at
`

type PostUpdateParams struct {
	ID      uuid.UUID
	Title   string
	Content string
}

func (q *Queries) PostUpdate(ctx context.Context, arg PostUpdateParams) (Post, error) {
	row := q.db.QueryRow(ctx, postUpdate, arg.ID, arg.Title, arg.Content)
	var i Post
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Content,
		&i.CreatedByID,
		&i.CommentsCount,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const postsCount = `-- name: PostsCount :one
select count(*) from posts 
where deleted_at is null
`

func (q *Queries) PostsCount(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, postsCount)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const postsList = `-- name: PostsList :many
select 
	p.id,
  p.title,
  p.content,
  p.created_by_id,
  u.name as created_by_name,
  p.comments_count,
  p.created_at,
  p.updated_at
from posts p
join users u on u.id = p.created_by_id
where p.deleted_at is null
order by p.created_at desc
limit $1
offset $2
`

type PostsListParams struct {
	Limit  int32
	Offset int32
}

type PostsListRow struct {
	ID            uuid.UUID
	Title         string
	Content       string
	CreatedByID   uuid.UUID
	CreatedByName string
	CommentsCount int32
	CreatedAt     pgtype.Timestamp
	UpdatedAt     pgtype.Timestamp
}

func (q *Queries) PostsList(ctx context.Context, arg PostsListParams) ([]PostsListRow, error) {
	rows, err := q.db.Query(ctx, postsList, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PostsListRow
	for rows.Next() {
		var i PostsListRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Content,
			&i.CreatedByID,
			&i.CreatedByName,
			&i.CommentsCount,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
